// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Result of opening a PDF document natively.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PdfOpenResultMessage: Hashable, CustomStringConvertible {
  /// Opaque handle identifying the open document on the native side.
  var handle: String
  /// Number of pages in the document.
  var pageCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PdfOpenResultMessage? {
    let handle = pigeonVar_list[0] as! String
    let pageCount = pigeonVar_list[1] as! Int64

    return PdfOpenResultMessage(
      handle: handle,
      pageCount: pageCount
    )
  }
  func toList() -> [Any?] {
    return [
      handle,
      pageCount,
    ]
  }
  static func == (lhs: PdfOpenResultMessage, rhs: PdfOpenResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.handle, rhs.handle) && MessagesPigeonInternal.deepEquals(lhs.pageCount, rhs.pageCount)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PdfOpenResultMessage")
    MessagesPigeonInternal.deepHash(value: handle, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pageCount, hasher: &hasher)
  }

  public var description: String {
    return "PdfOpenResultMessage(handle: \(String(describing: handle)), pageCount: \(String(describing: pageCount)))"
  }
}

/// Result of an "open externally" request (hand the file to another app).
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeOpenResultMessage: Hashable, CustomStringConvertible {
  var success: Bool
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeOpenResultMessage? {
    let success = pigeonVar_list[0] as! Bool
    let message: String? = nilOrValue(pigeonVar_list[1])

    return NativeOpenResultMessage(
      success: success,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      message,
    ]
  }
  static func == (lhs: NativeOpenResultMessage, rhs: NativeOpenResultMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.success, rhs.success) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeOpenResultMessage")
    MessagesPigeonInternal.deepHash(value: success, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
  }

  public var description: String {
    return "NativeOpenResultMessage(success: \(String(describing: success)), message: \(String(describing: message)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return PdfOpenResultMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeOpenResultMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PdfOpenResultMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeOpenResultMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// PDF (open/renderPage/close). Replaces `pdfx`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PdfHostApi {
  func open(path: String) async throws -> PdfOpenResultMessage
  func renderPage(handle: String, index: Int64, width: Int64, height: Int64) async throws -> FlutterStandardTypedData
  func close(handle: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PdfHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PdfHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PdfHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.PdfHostApi.open\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.open(path: pathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChannel.setMessageHandler(nil)
    }
    let renderPageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.PdfHostApi.renderPage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renderPageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        let indexArg = args[1] as! Int64
        let widthArg = args[2] as! Int64
        let heightArg = args[3] as! Int64
        Task { @MainActor in
          do {
            let result = try await api.renderPage(handle: handleArg, index: indexArg, width: widthArg, height: heightArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      renderPageChannel.setMessageHandler(nil)
    }
    let closeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.PdfHostApi.close\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.close(handle: handleArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeChannel.setMessageHandler(nil)
    }
  }
}
/// Audio playback control (load/play/pause/seek/setSpeed/setVolume/dispose).
/// Replaces `just_audio`. Playback-state events stay on a hand-written
/// per-`playerId` `EventChannel` — see the note at the top of this file.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AudioHostApi {
  func load(playerId: String, filePath: String?, url: String?) async throws
  func play(playerId: String) async throws
  func pause(playerId: String) async throws
  func seek(playerId: String, positionMs: Int64) async throws
  func setSpeed(playerId: String, speed: Double) async throws
  func setVolume(playerId: String, volume: Double) async throws
  func dispose(playerId: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AudioHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AudioHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AudioHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.load\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let filePathArg: String? = nilOrValue(args[1])
        let urlArg: String? = nilOrValue(args[2])
        Task { @MainActor in
          do {
            try await api.load(playerId: playerIdArg, filePath: filePathArg, url: urlArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.play(playerId: playerIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.pause(playerId: playerIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let positionMsArg = args[1] as! Int64
        Task { @MainActor in
          do {
            try await api.seek(playerId: playerIdArg, positionMs: positionMsArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    let setSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.setSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let speedArg = args[1] as! Double
        Task { @MainActor in
          do {
            try await api.setSpeed(playerId: playerIdArg, speed: speedArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setSpeedChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let volumeArg = args[1] as! Double
        Task { @MainActor in
          do {
            try await api.setVolume(playerId: playerIdArg, volume: volumeArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.AudioHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.dispose(playerId: playerIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// Video playback control (load/play/pause/seek/setSpeed/setVolume/dispose).
/// Replaces `video_player`'s control API. The platform-view factory that
/// embeds the native surface stays native/hand-registered (it isn't a
/// method call), and playback-state events stay on a hand-written
/// per-`playerId` `EventChannel` — see the note at the top of this file.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol VideoHostApi {
  func load(playerId: String, filePath: String?, url: String?) async throws
  func play(playerId: String) async throws
  func pause(playerId: String) async throws
  func seek(playerId: String, positionMs: Int64) async throws
  func setSpeed(playerId: String, speed: Double) async throws
  func setVolume(playerId: String, volume: Double) async throws
  func dispose(playerId: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class VideoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `VideoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: VideoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let loadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.load\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let filePathArg: String? = nilOrValue(args[1])
        let urlArg: String? = nilOrValue(args[2])
        Task { @MainActor in
          do {
            try await api.load(playerId: playerIdArg, filePath: filePathArg, url: urlArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadChannel.setMessageHandler(nil)
    }
    let playChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.play\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      playChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.play(playerId: playerIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      playChannel.setMessageHandler(nil)
    }
    let pauseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.pause\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pauseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.pause(playerId: playerIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      pauseChannel.setMessageHandler(nil)
    }
    let seekChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.seek\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      seekChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let positionMsArg = args[1] as! Int64
        Task { @MainActor in
          do {
            try await api.seek(playerId: playerIdArg, positionMs: positionMsArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      seekChannel.setMessageHandler(nil)
    }
    let setSpeedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.setSpeed\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSpeedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let speedArg = args[1] as! Double
        Task { @MainActor in
          do {
            try await api.setSpeed(playerId: playerIdArg, speed: speedArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setSpeedChannel.setMessageHandler(nil)
    }
    let setVolumeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.setVolume\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setVolumeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        let volumeArg = args[1] as! Double
        Task { @MainActor in
          do {
            try await api.setVolume(playerId: playerIdArg, volume: volumeArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setVolumeChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.VideoHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let playerIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.dispose(playerId: playerIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
/// Share (shareFile/shareText). Replaces `share_plus`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ShareHostApi {
  func shareFile(path: String, text: String?) async throws
  func shareText(text: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ShareHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ShareHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ShareHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let shareFileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.ShareHostApi.shareFile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shareFileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let textArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            try await api.shareFile(path: pathArg, text: textArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      shareFileChannel.setMessageHandler(nil)
    }
    let shareTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.ShareHostApi.shareText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shareTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.shareText(text: textArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      shareTextChannel.setMessageHandler(nil)
    }
  }
}
/// Open externally (hand the file to another app via the OS chooser).
/// Replaces `open_filex`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OpenHostApi {
  func openExternally(path: String, mimeType: String?) async throws -> NativeOpenResultMessage
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OpenHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `OpenHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OpenHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openExternallyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.OpenHostApi.openExternally\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openExternallyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let mimeTypeArg: String? = nilOrValue(args[1])
        Task { @MainActor in
          do {
            let result = try await api.openExternally(path: pathArg, mimeType: mimeTypeArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openExternallyChannel.setMessageHandler(nil)
    }
  }
}
/// In-app Office document preview (iOS/macOS QuickLook). Android has no
/// native in-app viewer and falls back to [OpenHostApi.openExternally] at
/// the Dart layer, so Android does not need to implement this API.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OfficeHostApi {
  func openOfficePreview(path: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OfficeHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `OfficeHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OfficeHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openOfficePreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.OfficeHostApi.openOfficePreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openOfficePreviewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.openOfficePreview(path: pathArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      openOfficePreviewChannel.setMessageHandler(nil)
    }
  }
}
/// App-private storage directories. Replaces `path_provider`.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PathsHostApi {
  func getApplicationSupportDirectory() async throws -> String
  func getApplicationCacheDirectory() async throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PathsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PathsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PathsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getApplicationSupportDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.PathsHostApi.getApplicationSupportDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getApplicationSupportDirectoryChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getApplicationSupportDirectory()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getApplicationSupportDirectoryChannel.setMessageHandler(nil)
    }
    let getApplicationCacheDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.PathsHostApi.getApplicationCacheDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getApplicationCacheDirectoryChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getApplicationCacheDirectory()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getApplicationCacheDirectoryChannel.setMessageHandler(nil)
    }
  }
}
/// Download start/resume/cancel. Replaces `dio`. Progress/completion/error
/// events stay on a hand-written shared `EventChannel` — see the note at
/// the top of this file.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DownloadHostApi {
  func startDownload(url: String, headers: [String: String], destPath: String) async throws -> String
  func resumeDownload(url: String, headers: [String: String], destPath: String) async throws -> String
  func cancelDownload(downloadId: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DownloadHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DownloadHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DownloadHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.DownloadHostApi.startDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let headersArg = args[1] as! [String: String]
        let destPathArg = args[2] as! String
        Task { @MainActor in
          do {
            let result = try await api.startDownload(url: urlArg, headers: headersArg, destPath: destPathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDownloadChannel.setMessageHandler(nil)
    }
    let resumeDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.DownloadHostApi.resumeDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resumeDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let urlArg = args[0] as! String
        let headersArg = args[1] as! [String: String]
        let destPathArg = args[2] as! String
        Task { @MainActor in
          do {
            let result = try await api.resumeDownload(url: urlArg, headers: headersArg, destPath: destPathArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      resumeDownloadChannel.setMessageHandler(nil)
    }
    let cancelDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.attachment_engine_platform_interface.DownloadHostApi.cancelDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let downloadIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.cancelDownload(downloadId: downloadIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelDownloadChannel.setMessageHandler(nil)
    }
  }
}
