# See Dependabot documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all-github-actions:
        patterns: [ "*" ]
    labels:
      - "autosubmit"
      - "infra: dependencies"
      - "infra: workflows"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Dart & Flutter Pub packages
  - package-ecosystem: "pub"
    directory: "/packages/white_label_kit"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "p: white_label_kit"
      - "infra: dependencies"

  - package-ecosystem: "pub"
    directory: "/packages/dig_cli"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "p: dig_cli"
      - "infra: dependencies"

  - package-ecosystem: "pub"
    directory: "/packages/apple_sign_in_plugin/apple_sign_in_plugin"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "p: apple_sign_in_plugin"
      - "infra: dependencies"

  - package-ecosystem: "pub"
    directory: "/packages/apple_sign_in_plugin/apple_sign_in_plugin_platform_interface"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "p: apple_sign_in_plugin"
      - "infra: dependencies"

  - package-ecosystem: "pub"
    directory: "/script/tool"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    labels:
      - "infra: dependencies"
      - "infra: workflows"
