'p: apple_sign_in_plugin':
  - changed-files:
    - any-glob-to-any-file:
      - packages/apple_sign_in_plugin/apple_sign_in_plugin/**/*

'p: apple_sign_in_plugin_darwin':
  - changed-files:
    - any-glob-to-any-file:
      - packages/apple_sign_in_plugin/apple_sign_in_plugin_darwin/**/*

'p: apple_sign_in_plugin_platform_interface':
  - changed-files:
    - any-glob-to-any-file:
      - packages/apple_sign_in_plugin/apple_sign_in_plugin_platform_interface/**/*

'p: dig_cli':
  - changed-files:
    - any-glob-to-any-file:
      - packages/dig_cli/**/*

'p: white_label_kit':
  - changed-files:
    - any-glob-to-any-file:
      - packages/white_label_kit/**/*
