// Copyright 2026 DHC Tech
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.
//
// NOTE: This file has NOT been compiled or verified on this machine (no
// native Linux toolchain / pkg-config / gtk+-3.0 headers available here).
// It mirrors the public plugin header shape generated by
// `flutter create --template=plugin --platforms=linux`
// (`FlutterPluginRegistrar`-based `<plugin>_register_with_registrar`).

#ifndef PACKAGES_ATTACHMENT_ENGINE_LINUX_LINUX_INCLUDE_ATTACHMENT_ENGINE_LINUX_ATTACHMENT_ENGINE_LINUX_PLUGIN_H_
#define PACKAGES_ATTACHMENT_ENGINE_LINUX_LINUX_INCLUDE_ATTACHMENT_ENGINE_LINUX_ATTACHMENT_ENGINE_LINUX_PLUGIN_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

#ifdef FLUTTER_PLUGIN_IMPL
#define FLUTTER_PLUGIN_EXPORT __attribute__((visibility("default")))
#else
#define FLUTTER_PLUGIN_EXPORT
#endif

typedef struct _AttachmentEngineLinuxPlugin AttachmentEngineLinuxPlugin;
typedef struct {
  GObjectClass parent_class;
} AttachmentEngineLinuxPluginClass;

FLUTTER_PLUGIN_EXPORT GType attachment_engine_linux_plugin_get_type();

#define ATTACHMENT_ENGINE_LINUX_PLUGIN_TYPE \
  (attachment_engine_linux_plugin_get_type())
#define ATTACHMENT_ENGINE_LINUX_PLUGIN(obj)                           \
  (G_TYPE_CHECK_INSTANCE_CAST((obj), ATTACHMENT_ENGINE_LINUX_PLUGIN_TYPE, \
                               AttachmentEngineLinuxPlugin))

FLUTTER_PLUGIN_EXPORT void attachment_engine_linux_plugin_register_with_registrar(
    FlPluginRegistrar* registrar);

G_END_DECLS

#endif  // PACKAGES_ATTACHMENT_ENGINE_LINUX_LINUX_INCLUDE_ATTACHMENT_ENGINE_LINUX_ATTACHMENT_ENGINE_LINUX_PLUGIN_H_
