name: apple_sign_in_plugin_web
description: Web implementation of the apple_sign_in_plugin package, using Apple's official Sign in with Apple JS SDK via JS interop.
repository: https://github.com/dhc-tech/flutter-packages/tree/main/packages/apple_sign_in_plugin/apple_sign_in_plugin_web
issue_tracker: https://github.com/dhc-tech/flutter-packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+apple_sign_in_plugin_web%22
version: 0.0.1-dev.0

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.16.0"

flutter:
  plugin:
    implements: apple_sign_in_plugin
    platforms:
      web:
        pluginClass: AppleSignInPluginWeb
        fileName: apple_sign_in_plugin_web.dart

dependencies:
  apple_sign_in_plugin_platform_interface: ^0.0.1-dev.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0

dev_dependencies:
  flutter_lints: '>=6.0.0 <8.0.0'
  flutter_test:
    sdk: flutter
  test: ^1.25.0

topics:
  - apple-sign-in
  - authentication
  - web
