name: apple_sign_in_plugin_web_example
description: "Example app exercising the apple_sign_in_plugin_web platform implementation directly."
publish_to: 'none' # This package is not intended for publishing.

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  apple_sign_in_plugin_platform_interface:
    path: ../../apple_sign_in_plugin_platform_interface
  apple_sign_in_plugin_web:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
