// Copyright 2026 DHC Tech
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.
//
// NOTE: This file has NOT been compiled or verified on this machine (no
// native Windows toolchain — no cl.exe/msbuild — is available here, and
// `flutter create --platforms=windows` refuses to scaffold a native
// template in this environment). It closely mirrors the plugin registrant
// shape generated by `flutter create --template=plugin --platforms=windows`
// and used by real published Windows Flutter plugins (e.g.
// `url_launcher_windows`, `file_selector_windows` on pub.dev). It needs a
// real Windows build (local machine or CI) to confirm it actually compiles
// and registers correctly.

#ifndef PACKAGES_ATTACHMENT_ENGINE_WINDOWS_WINDOWS_ATTACHMENT_ENGINE_WINDOWS_PLUGIN_H_
#define PACKAGES_ATTACHMENT_ENGINE_WINDOWS_WINDOWS_ATTACHMENT_ENGINE_WINDOWS_PLUGIN_H_

#include <flutter/method_channel.h>
#include <flutter/plugin_registrar_windows.h>

#include <memory>

#include "audio_channel.h"
#include "share_channel.h"
#include "video_channel.h"

namespace attachment_engine_windows {

// Registers the `attachment_engine/share`, `attachment_engine/audio`, and
// `attachment_engine/video` MethodChannel/EventChannel pairs (and the
// `attachment_engine/video_view` PlatformViewFactory), matching the exact
// channel names used by the Android (Kotlin) and iOS (Swift)
// implementations of this plugin. Paths/open-externally/download stay pure
// Dart (path_provider/url_launcher/dart:io), so they are NOT registered
// here.
class AttachmentEngineWindowsPlugin : public flutter::Plugin {
 public:
  static void RegisterWithRegistrar(flutter::PluginRegistrarWindows* registrar);

  explicit AttachmentEngineWindowsPlugin(flutter::PluginRegistrarWindows* registrar);
  virtual ~AttachmentEngineWindowsPlugin();

  AttachmentEngineWindowsPlugin(const AttachmentEngineWindowsPlugin&) = delete;
  AttachmentEngineWindowsPlugin& operator=(const AttachmentEngineWindowsPlugin&) = delete;

 private:
  std::unique_ptr<ShareChannel> share_channel_;
  std::unique_ptr<AudioChannel> audio_channel_;
  std::unique_ptr<VideoChannel> video_channel_;
};

}  // namespace attachment_engine_windows

#endif  // PACKAGES_ATTACHMENT_ENGINE_WINDOWS_WINDOWS_ATTACHMENT_ENGINE_WINDOWS_PLUGIN_H_
