builders:
  white_label_generator:
    import: "package:white_label_kit/builder.dart"
    builder_factories: ["whiteLabelBuilder"]
    build_extensions: {"white_label.yaml": ["lib/white_label.g.dart"]}
    auto_apply: dependents
    build_to: source
    required_inputs: []
