// Copyright 2026 DHC Tech
// Use of this source code is governed by an MIT-style license that can be
// found in the LICENSE file.

/// Generates `lib/white_label.g.dart` — a plain, directly-invoked step (via
/// the `generate` CLI command, see `bin/white_label.dart`), the same way
/// `flutter_native_splash:create`/`icons_launcher:create` generate their
/// output files: run one command, get one file, no `build_runner`/
/// `build.yaml` involved. `white_label.yaml` stays at the project root —
/// same place a developer already looks for `pubspec.yaml`.
///
/// SECURITY-CRITICAL DESIGN NOTE (read before changing this file): an
/// earlier version of this generator (when it was a `build_runner` builder)
/// emitted *every* declared tenant's fully resolved [WhiteLabelRuntime] into
/// one compile-time `Map`, so an app could pick the right one for whatever
/// flavor it was actually running as. That is a real tenant-isolation
/// vulnerability for any app where each build is meant to ship only ONE
/// tenant's branding/config — every OTHER tenant's data (API URLs, theme,
/// bundle ids, feature flags) would still be baked into every build's
/// compiled binary. This generator emits exactly ONE tenant's resolved
/// [WhiteLabelRuntime], never a map of all of them. See
/// `test/dart_config_generator_test.dart`'s "does not leak other tenants'
/// data" regression test.
library;

import 'dart:io';

import '../config/tenant_config.dart';
import '../config/white_label_config.dart';
import '../runtime/white_label_runtime.dart';

/// Resolves which tenant a `generate` run is for: [explicitTenantId] (the
/// CLI's `--tenant` flag) wins if given; otherwise the `TENANT_ID`
/// environment variable (same variable name this ecosystem's apps already
/// use for `String.fromEnvironment('TENANT_ID', ...)` in the compiled app
/// itself — set by whatever build script invokes `generate`, e.g.
/// `tool/build_runner.dart`'s `regenerateWhiteLabelG`); otherwise
/// `default_tenant`, so a plain `dart run white_label_kit:generate` with no
/// flag/environment variable still works during day-to-day development.
String resolveGeneratorTenantId(
  WhiteLabelConfig config, {
  String? explicitTenantId,
  Map<String, String>? environment,
}) {
  if (explicitTenantId != null) {
    if (config.has(explicitTenantId)) {
      return explicitTenantId;
    }
    throw ArgumentError.value(
      explicitTenantId,
      'explicitTenantId',
      'No such tenant in white_label.yaml',
    );
  }
  final Map<String, String> env = environment ?? Platform.environment;
  final String? envTenantId = env['TENANT_ID'];
  if (envTenantId != null && config.has(envTenantId)) {
    return envTenantId;
  }
  return config.defaultTenant;
}

/// Generates the `lib/white_label.g.dart` source text for [config]'s
/// tenant [tenantId] — a pure function (no file I/O) so it's directly
/// testable; see [writeGeneratedFile] for the CLI's actual file-writing
/// entry point.
String generateWhiteLabelSource(WhiteLabelConfig config, String tenantId) {
  final List<String> tenantIds = config.tenants.keys.toList()..sort();
  final TenantConfig selected = config[tenantId];

  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND')
    ..writeln('//')
    ..writeln('// Generated by `dart run white_label_kit:generate` from')
    ..writeln('// white_label.yaml for tenant "$tenantId" — re-run after')
    ..writeln('// editing white_label.yaml or changing tenants.')
    ..writeln('//')
    ..writeln('// SECURITY: only "$tenantId"\'s data is in this file — see')
    ..writeln("// lib/src/generation/dart_config_generator.dart's doc")
    ..writeln('// comment for why that matters.')
    ..writeln()
    ..writeln("import 'package:white_label_kit/white_label_kit.dart';")
    ..writeln()
    ..writeln('/// The `default_tenant` declared in white_label.yaml.')
    ..writeln(
      'const String whiteLabelDefaultTenant = ${_dartString(config.defaultTenant)};',
    )
    ..writeln()
    ..writeln(
      '/// Every tenant id declared in white_label.yaml, sorted — NAMES\n'
      '/// only, not their config. Fine to ship in every build; use this\n'
      '/// for things like a tenant picker in an internal/dev build, not\n'
      "/// for reading another tenant's actual data (which isn't here).",
    )
    ..writeln(
      'const List<String> whiteLabelTenantIds = ${_dartStringList(tenantIds)};',
    )
    ..writeln()
    ..writeln(
      "/// This build's tenant, resolved when `generate` last ran (see\n"
      "/// resolveGeneratorTenantId) — the ONLY tenant's data in this file.",
    )
    ..writeln(
      'const WhiteLabelRuntime whiteLabelRuntime = ${_runtimeLiteral(selected)};',
    );

  return buffer.toString();
}

/// Writes [generateWhiteLabelSource]'s output to `<projectRoot>/lib/white_label.g.dart`.
void writeGeneratedFile(
  String projectRoot,
  WhiteLabelConfig config,
  String tenantId,
) {
  final file = File('$projectRoot/lib/white_label.g.dart');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(generateWhiteLabelSource(config, tenantId));
}

/// Renders a `const WhiteLabelRuntime(...)` source literal for [config],
/// mirroring [WhiteLabelRuntime.fromConfig]'s field mapping exactly (kept
/// as a separate, parallel implementation because this one emits Dart
/// *source text*, not live objects — see
/// `test/dart_config_generator_test.dart`'s "generated WhiteLabelRuntime
/// matches WhiteLabelRuntime.fromConfig" test, which pins the two mappings
/// together so they can't silently drift).
String _runtimeLiteral(TenantConfig config) {
  final TenantVersion androidVersion = config.androidVersion;
  final TenantVersion iosVersion = config.iosVersion;
  return 'WhiteLabelRuntime('
      'tenantId: ${_dartString(config.id)}, '
      'tenantName: ${_dartString(config.name)}, '
      'theme: WhiteLabelTheme(primaryColorHex: '
      '${_dartStringOrNull(config.theme.primaryColor)}, '
      'secondaryColorHex: ${_dartStringOrNull(config.theme.secondaryColor)}, '
      'brandColors: ${_dartStringMap(config.theme.brandColors)}, '
      'featureColors: ${_dartStringMap(config.theme.featureColors)}, '
      'sectionColors: ${_dartStringMap(config.theme.sectionColors)}, '
      'gradientColors: ${_dartStringMap(config.theme.gradientColors)}'
      '), environment: WhiteLabelEnvironment(apiBaseUrl: '
      '${_dartStringOrNull(config.environment.apiBaseUrl)}'
      '), features: ${_dartBoolMap(config.features)}, '
      'android: WhiteLabelAndroidInfo(applicationId: '
      '${_dartString(config.android.applicationId)}, '
      'appName: ${_dartString(config.android.appName)}, version: '
      'WhiteLabelVersion('
      'name: ${_dartString(androidVersion.name)}, '
      'buildNumber: ${androidVersion.buildNumber}'
      ')'
      '), ios: WhiteLabelIosInfo(bundleId: '
      '${_dartString(config.ios.bundleId)}, '
      'appName: ${_dartString(config.ios.appName)}, version: '
      'WhiteLabelVersion('
      'name: ${_dartString(iosVersion.name)}, '
      'buildNumber: ${iosVersion.buildNumber}'
      ')'
      ')'
      ')';
}

String _dartString(String value) => "'${value.replaceAll("'", r"\'")}'";

String _dartStringOrNull(String? value) =>
    value == null ? 'null' : _dartString(value);

String _dartStringList(Iterable<String> values) =>
    '[${values.map(_dartString).join(', ')}]';

String _dartBoolMap(Map<String, bool> values) =>
    '{'
    '${values.entries.map((e) => '${_dartString(e.key)}: ${e.value}').join(', ')}'
    '}';

String _dartStringMap(Map<String, String> values) =>
    '{'
    '${values.entries.map((e) => '${_dartString(e.key)}: ${_dartString(e.value)}').join(', ')}'
    '}';
